import { format, subDays } from 'date-fns'
import { Activity, Brain, Droplets, Moon, Plus, ShieldAlert } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { Button, EmptyState, Modal } from '../components/common'
import { PageHeader } from '../components/layout'
import { usePageCapture } from '../hooks/usePageCapture'
import { useFaroStore } from '../store'

export function HealthPage() {
  const { capture } = usePageCapture()
  const logs = useFaroStore((state) => state.healthLogs)
  const treatments = useFaroStore((state) => state.treatmentLogs)
  const createHealth = useFaroStore((state) => state.createHealthLog)
  const createTreatment = useFaroStore((state) => state.createTreatmentLog)
  const [healthOpen, setHealthOpen] = useState(false)
  const [treatmentOpen, setTreatmentOpen] = useState(false)
  const recent = logs.filter((item) => new Date(item.occurredAt) >= subDays(new Date(), 29))
  const average = (getter: (item: typeof logs[number]) => number | undefined) => { const values = recent.flatMap((item) => getter(item) == null ? [] : [getter(item)!]); return values.length ? values.reduce((sum, value) => sum + value, 0) / values.length : 0 }
  const series = [...logs].sort((a, b) => a.occurredAt.localeCompare(b.occurredAt)).slice(-14).map((item) => ({ date: format(new Date(`${item.occurredAt.slice(0, 10)}T12:00:00`), 'dd MMM'), weight: item.weightKg, mood: item.mood, sleep: item.sleepHours }))
  return <div className="page tracker-page"><PageHeader eyebrow="Salud" title="Observa. Registra. Cuídate." description="Tendencias personales para conocerte mejor, sin diagnósticos." onCapture={capture} />
    <section className="tracker-metrics health-metrics"><div><Moon /><span>Sueño promedio</span><strong>{average((item) => item.sleepHours).toFixed(1)} h</strong></div><div><Brain /><span>Ánimo promedio</span><strong>{average((item) => item.mood).toFixed(1)}/10</strong></div><div><Activity /><span>Entrenamiento</span><strong>{recent.filter((item) => (item.trainingMinutes ?? 0) > 0).length} días</strong></div><div><Droplets /><span>Agua promedio</span><strong>{average((item) => item.waterLiters).toFixed(1)} L</strong></div><Button icon={<Plus size={15} />} onClick={() => setHealthOpen(true)}>Registro diario</Button></section>
    <section className="chart-panel chart-panel--wide"><div className="section-heading"><div><span className="eyebrow">Tendencias</span><h2>Peso, ánimo y sueño</h2></div></div>{series.length ? <div className="chart-box chart-box--tall" aria-label="Tendencias de salud"><ResponsiveContainer width="100%" height="100%"><LineChart data={series} accessibilityLayer><CartesianGrid stroke="#1d1d22" vertical={false} /><XAxis dataKey="date" stroke="#66666e" tickLine={false} axisLine={false} fontSize={9} /><YAxis yAxisId="wellness" domain={[0, 10]} stroke="#66666e" tickLine={false} axisLine={false} fontSize={9} /><YAxis yAxisId="weight" orientation="right" domain={['dataMin - 1', 'dataMax + 1']} stroke="#66666e" tickLine={false} axisLine={false} fontSize={9} /><Tooltip contentStyle={{ background: '#111114', border: '1px solid #303038', borderRadius: 8, fontSize: 10 }} /><Line yAxisId="wellness" type="monotone" dataKey="mood" name="Ánimo" stroke="#2457ff" strokeWidth={2} connectNulls /><Line yAxisId="wellness" type="monotone" dataKey="sleep" name="Sueño" stroke="#35c78a" connectNulls /><Line yAxisId="weight" type="monotone" dataKey="weight" name="Peso" stroke="#f4b740" connectNulls /></LineChart></ResponsiveContainer></div> : <EmptyState title="Sin tendencias" description="Registra tu primer día para comenzar." />}</section>
    <section className="treatment-panel"><div className="treatment-panel__copy"><ShieldAlert /><div><span className="eyebrow">Subsección separada</span><h2>Isotretinoína</h2><p>Este registro es informativo y no sustituye las indicaciones de tu dermatólogo.</p></div></div><Button variant="secondary" icon={<Plus size={14} />} onClick={() => setTreatmentOpen(true)}>Registrar tratamiento</Button>{treatments.length > 0 && <div className="treatment-history">{[...treatments].reverse().slice(0, 5).map((item) => <article key={item.id}><strong>{item.occurredAt.slice(0, 10)}</strong><span>{item.medicationTaken ? 'Medicamento registrado' : 'No tomado'}{item.dosage ? ` · ${item.dosage}` : ''}</span><small>{item.skinCondition || 'Sin nota de piel'}{item.sideEffects ? ` · ${item.sideEffects}` : ''}</small></article>)}</div>}</section>
    <section className="history-panel"><div className="section-heading"><div><span className="eyebrow">Historial</span><h2>Registros diarios</h2></div></div>{[...logs].sort((a, b) => b.occurredAt.localeCompare(a.occurredAt)).map((item) => <article className="history-row" key={item.id}><div><strong>Ánimo {item.mood ?? '—'} · Energía {item.energy}/10</strong><small>{item.sleepHours ? `${item.sleepHours} h sueño` : 'Sueño sin registrar'}{item.trainingMinutes ? ` · ${item.trainingMinutes} min entrenamiento` : ''}{item.meditationMinutes ? ` · ${item.meditationMinutes} min meditación` : ''}</small></div><span>{item.weightKg ? `${item.weightKg} kg` : '—'}</span><time>{item.occurredAt.slice(0, 10)}</time></article>)}</section>
    {healthOpen && <HealthLogDialog onClose={() => setHealthOpen(false)} onSave={createHealth} />}
    {treatmentOpen && <TreatmentDialog onClose={() => setTreatmentOpen(false)} onSave={createTreatment} />}
  </div>
}

function HealthLogDialog({ onClose, onSave }: { onClose: () => void; onSave: ReturnType<typeof useFaroStore.getState>['createHealthLog'] }) {
  const [values, setValues] = useState({ date: format(new Date(), 'yyyy-MM-dd'), weight: '', sleep: '7', mood: '7', energy: '7', anxiety: '3', water: '2', training: '0', meditation: '0', notes: '' })
  const set = (key: keyof typeof values, value: string) => setValues((current) => ({ ...current, [key]: value }))
  const submit = (event: FormEvent) => { event.preventDefault(); const timestamp = new Date().toISOString(); onSave({ id: crypto.randomUUID(), area: 'health', occurredAt: values.date, weightKg: values.weight ? Number(values.weight) : undefined, sleepHours: Number(values.sleep), mood: Number(values.mood), energy: Number(values.energy), anxiety: Number(values.anxiety), waterLiters: Number(values.water), trainingMinutes: Number(values.training), movementMinutes: Number(values.training), meditationMinutes: Number(values.meditation), notes: values.notes || undefined, createdAt: timestamp, updatedAt: timestamp }); onClose() }
  return <Modal open title="Registro diario de salud" onClose={onClose}><form className="tracker-form" onSubmit={submit}><div className="tracker-form__grid"><label>Fecha<input autoFocus type="date" required value={values.date} onChange={(event) => set('date', event.target.value)} /></label><label>Peso (kg) <span>opcional</span><input type="number" step=".1" value={values.weight} onChange={(event) => set('weight', event.target.value)} /></label><label>Sueño (horas)<input type="number" min="0" max="24" step=".5" value={values.sleep} onChange={(event) => set('sleep', event.target.value)} /></label><label>Agua (litros)<input type="number" min="0" step=".1" value={values.water} onChange={(event) => set('water', event.target.value)} /></label><label>Ánimo 1–10<input type="number" min="1" max="10" value={values.mood} onChange={(event) => set('mood', event.target.value)} /></label><label>Energía 1–10<input type="number" min="1" max="10" value={values.energy} onChange={(event) => set('energy', event.target.value)} /></label><label>Ansiedad 1–10<input type="number" min="1" max="10" value={values.anxiety} onChange={(event) => set('anxiety', event.target.value)} /></label><label>Entrenamiento (min)<input type="number" min="0" value={values.training} onChange={(event) => set('training', event.target.value)} /></label><label>Meditación (min)<input type="number" min="0" value={values.meditation} onChange={(event) => set('meditation', event.target.value)} /></label></div><label>Notas <span>opcional</span><textarea rows={2} value={values.notes} onChange={(event) => set('notes', event.target.value)} /></label><div className="modal-actions"><Button type="button" variant="ghost" onClick={onClose}>Cancelar</Button><Button type="submit">Guardar salud</Button></div></form></Modal>
}

function TreatmentDialog({ onClose, onSave }: { onClose: () => void; onSave: ReturnType<typeof useFaroStore.getState>['createTreatmentLog'] }) {
  const [date, setDate] = useState(format(new Date(), 'yyyy-MM-dd')); const [taken, setTaken] = useState(true); const [dosage, setDosage] = useState(''); const [dryness, setDryness] = useState(''); const [skin, setSkin] = useState(''); const [effects, setEffects] = useState(''); const [notes, setNotes] = useState('')
  const submit = (event: FormEvent) => { event.preventDefault(); const timestamp = new Date().toISOString(); onSave({ id: crypto.randomUUID(), area: 'health', treatment: 'isotretinoin', occurredAt: date, medicationTaken: taken, dosage: dosage || undefined, dryness: dryness ? Number(dryness) : undefined, skinCondition: skin || undefined, sideEffects: effects || undefined, notes: notes || undefined, createdAt: timestamp, updatedAt: timestamp }); onClose() }
  return <Modal open title="Registro de isotretinoína" onClose={onClose}><form className="tracker-form" onSubmit={submit}><div className="medical-notice">Este registro es informativo y no sustituye las indicaciones de tu dermatólogo.</div><label>Fecha<input autoFocus type="date" required value={date} onChange={(event) => setDate(event.target.value)} /></label><label className="check-label"><input type="checkbox" checked={taken} onChange={(event) => setTaken(event.target.checked)} /> Medicamento tomado</label><label>Dosis escrita por ti <span>opcional</span><input value={dosage} onChange={(event) => setDosage(event.target.value)} placeholder="Sólo registra la indicación recibida" /></label><div className="tracker-form__grid"><label>Resequedad 1–10<input type="number" min="1" max="10" value={dryness} onChange={(event) => setDryness(event.target.value)} /></label><label>Estado de piel<input value={skin} onChange={(event) => setSkin(event.target.value)} /></label></div><label>Efectos secundarios <span>opcional</span><input value={effects} onChange={(event) => setEffects(event.target.value)} /></label><label>Notas <span>opcional</span><textarea rows={2} value={notes} onChange={(event) => setNotes(event.target.value)} /></label><div className="modal-actions"><Button type="button" variant="ghost" onClick={onClose}>Cancelar</Button><Button type="submit">Guardar registro</Button></div></form></Modal>
}
