import { BriefcaseBusiness, Plus, Send, Trash2 } from 'lucide-react'
import { useCallback, useState, type FormEvent } from 'react'
import { Button, EmptyState, Modal, ProgressBar } from '../components/common'
import { PageHeader } from '../components/layout'
import { useRepositoryList } from '../hooks/useRepositoryList'
import { usePageCapture } from '../hooks/usePageCapture'
import { contentItemRepository, portfolioCaseStudyRepository, portfolioProjectRepository } from '../repositories/growthRepositories'
import type { Database } from '../types/database.types'

type Project = Database['public']['Tables']['portfolio_projects']['Row']
type CaseStudy = Database['public']['Tables']['portfolio_case_studies']['Row']

export function PortfolioPage() {
  const projectLoader = useCallback((userId: string) => portfolioProjectRepository.list(userId), [])
  const { capture } = usePageCapture()
  const caseLoader = useCallback((userId: string) => portfolioCaseStudyRepository.list(userId), [])
  const projects = useRepositoryList(projectLoader), cases = useRepositoryList(caseLoader)
  const [editing, setEditing] = useState<Project>(), [caseEditing, setCaseEditing] = useState<CaseStudy>()
  const [feedback, setFeedback] = useState('')
  const progress = (project: Project) => Math.round([project.description, project.problem, project.solution, project.impact, project.technologies.length, project.client, project.role].filter(Boolean).length / 7 * 100)
  return <div className="page growth-page"><PageHeader eyebrow="Evidencia profesional y comercial" title="Portfolio" description="Convierte trabajo real en proyectos y casos de estudio publicables." onCapture={capture} />
    <div className="growth-toolbar"><section className="growth-metrics growth-metrics--inline"><Metric label="Proyectos" value={`${projects.data.length}`} /><Metric label="Publicados" value={`${projects.data.filter((item) => item.status === 'published').length}`} /><Metric label="Borradores" value={`${projects.data.filter((item) => item.status === 'draft').length}`} /><Metric label="Casos incompletos" value={`${projects.data.filter((item) => progress(item) < 100).length}`} /></section><Button icon={<Plus size={15} />} onClick={() => setEditing(blankProject())}>Nuevo proyecto</Button></div>
    {feedback && <div className="kanban-feedback" role="status">{feedback}</div>}
    {projects.loading && !projects.data.length ? <div className="planning-skeleton">Sincronizando portfolio…</div> : projects.error ? <EmptyState title="No pudimos cargar Portfolio" description={projects.error} action={<Button onClick={projects.refresh}>Reintentar</Button>} /> :
      projects.data.length ? <section className="portfolio-grid">{projects.data.map((project) => <article key={project.id}><header><BriefcaseBusiness /><span>{project.status}</span></header><h2>{project.title}</h2><p>{project.client || 'Proyecto personal'} · {project.role || 'Rol por definir'}</p><div className="journal-tags">{project.technologies.map((item) => <span key={item}>{item}</span>)}</div><ProgressBar value={progress(project)} /><small>{progress(project)}% documentado · actualizado {new Date(project.updated_at).toLocaleDateString('es-MX')}</small><footer><Button onClick={() => setEditing(project)}>Abrir / Editar</Button><Button variant="ghost" onClick={() => setCaseEditing(cases.data.find((item) => item.project_id === project.id) ?? blankCase(project.id))}>Caso de estudio</Button></footer></article>)}</section>
        : <EmptyState title="Tu trabajo merece evidencia" description="Documenta tu primer proyecto profesional." action={<Button onClick={() => setEditing(blankProject())}>Crear proyecto</Button>} />}
    {editing && <ProjectDialog item={editing} userId={projects.user?.id} onClose={() => setEditing(undefined)} onSaved={async () => { setEditing(undefined); await projects.refresh(); setFeedback('Proyecto guardado.') }} />}
    {caseEditing && <CaseDialog item={caseEditing} userId={cases.user?.id} onClose={() => setCaseEditing(undefined)} onSaved={async (item) => { setCaseEditing(undefined); await cases.refresh(); setFeedback('Caso de estudio guardado.'); return item }} />}
  </div>
}
function Metric({ label, value }: { label: string; value: string }) { return <article><BriefcaseBusiness /><span>{label}</span><strong>{value}</strong></article> }
function blankProject(): Project { const now = new Date().toISOString(); return { id: crypto.randomUUID(), user_id: '', title: '', client: null, role: null, description: null, problem: null, solution: null, impact: null, technologies: [], starts_on: null, ends_on: null, status: 'draft', links: {}, workspace_id: null, visibility: 'private', featured: false, created_at: now, updated_at: now } }
function blankCase(projectId: string): CaseStudy { const now = new Date().toISOString(); return { id: crypto.randomUUID(), user_id: '', project_id: projectId, context: null, problem: null, process: null, solution: null, result: null, metrics: null, learnings: null, testimonial: null, status: 'draft', sales_opportunity_id: null, created_at: now, updated_at: now } }
function ProjectDialog({ item, userId, onClose, onSaved }: { item: Project; userId?: string; onClose: () => void; onSaved: () => void }) {
  const [value, setValue] = useState(item)
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!userId) return; await portfolioProjectRepository.save({ ...value, user_id: userId }, userId); onSaved() }
  return <Modal open title={item.title ? 'Editar proyecto' : 'Nuevo proyecto'} onClose={onClose}><form className="growth-form growth-form--wide" onSubmit={submit}><label>Título<input autoFocus required value={value.title} onChange={(event) => setValue({ ...value, title: event.target.value })} /></label><div><label>Cliente<input value={value.client ?? ''} onChange={(event) => setValue({ ...value, client: event.target.value })} /></label><label>Rol<input value={value.role ?? ''} onChange={(event) => setValue({ ...value, role: event.target.value })} /></label></div><label>Descripción<textarea rows={2} value={value.description ?? ''} onChange={(event) => setValue({ ...value, description: event.target.value })} /></label><label>Problema<textarea rows={2} value={value.problem ?? ''} onChange={(event) => setValue({ ...value, problem: event.target.value })} /></label><label>Solución<textarea rows={2} value={value.solution ?? ''} onChange={(event) => setValue({ ...value, solution: event.target.value })} /></label><label>Impacto<textarea rows={2} value={value.impact ?? ''} onChange={(event) => setValue({ ...value, impact: event.target.value })} /></label><label>Tecnologías <span>separadas por comas</span><input value={value.technologies.join(', ')} onChange={(event) => setValue({ ...value, technologies: event.target.value.split(',').map((item) => item.trim()).filter(Boolean) })} /></label><div><label>Estado<select value={value.status} onChange={(event) => setValue({ ...value, status: event.target.value as Project['status'] })}><option value="draft">Borrador</option><option value="review">Revisión</option><option value="published">Publicado</option><option value="archived">Archivado</option></select></label><label>Visibilidad<select value={value.visibility} onChange={(event) => setValue({ ...value, visibility: event.target.value as Project['visibility'] })}><option value="private">Privado</option><option value="unlisted">No listado</option><option value="public">Público</option></select></label></div><div className="modal-actions">{item.title && <Button type="button" variant="ghost" icon={<Trash2 size={14} />} onClick={async () => { if (!userId) return; await portfolioProjectRepository.remove(item.id, userId); onSaved() }}>Eliminar</Button>}<Button type="button" variant="ghost" onClick={onClose}>Cancelar</Button><Button type="submit">Guardar</Button></div></form></Modal>
}
function CaseDialog({ item, userId, onClose, onSaved }: { item: CaseStudy; userId?: string; onClose: () => void; onSaved: (item: CaseStudy) => void }) {
  const [value, setValue] = useState(item)
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!userId) return; const saved = await portfolioCaseStudyRepository.save({ ...value, user_id: userId }, userId); onSaved(saved) }
  const createContent = async () => { if (!userId) return; await contentItemRepository.save({ user_id: userId, title: `Caso de estudio: ${value.context?.slice(0, 60) || 'Portfolio'}`, idea: value.result, format: 'Caso de estudio', status: 'idea', portfolio_case_study_id: value.id }, userId); setValue({ ...value }) }
  return <Modal open title="Caso de estudio" onClose={onClose}><form className="growth-form growth-form--wide" onSubmit={submit}>{(['context', 'problem', 'process', 'solution', 'result', 'metrics', 'learnings', 'testimonial'] as const).map((field) => <label key={field}>{({ context: 'Contexto', problem: 'Problema', process: 'Proceso', solution: 'Solución', result: 'Resultado', metrics: 'Métricas', learnings: 'Aprendizajes', testimonial: 'Testimonio' })[field]}<textarea rows={2} value={value[field] ?? ''} onChange={(event) => setValue({ ...value, [field]: event.target.value })} /></label>)}<label>Estado<select value={value.status} onChange={(event) => setValue({ ...value, status: event.target.value as CaseStudy['status'] })}><option value="draft">Borrador</option><option value="review">Revisión</option><option value="published">Publicado</option><option value="archived">Archivado</option></select></label><div className="modal-actions"><Button type="button" variant="ghost" icon={<Send size={14} />} onClick={() => void createContent()}>Crear contenido</Button><Button type="button" variant="ghost" onClick={onClose}>Cancelar</Button><Button type="submit">Guardar caso</Button></div></form></Modal>
}
