import { addDays, format, parseISO } from 'date-fns'
import { Check, Plus, Target, TimerReset, X } from 'lucide-react'
import { useMemo, useState, type FormEvent } from 'react'
import { Button, EmptyState, Modal, ProgressBar } from '../components/common'
import { PageHeader } from '../components/layout'
import type { Sprint, SprintCommitment, SprintOutcome, SprintReview } from '../features/sprints/sprintTypes'
import { usePageCapture } from '../hooks/usePageCapture'
import { useSprints } from '../hooks/useSprints'
import { sprintRepository } from '../repositories/sprintRepository'
import { useFaroStore } from '../store'

const commitmentLabels: Record<SprintCommitment, string> = { committed: 'Comprometidas', emergent: 'Emergentes', optional: 'Opcionales' }

export function SprintsPage() {
  const { capture } = usePageCapture(), { data, loading, error, refresh, user } = useSprints()
  const tasks = useFaroStore((state) => state.tasks), updateTask = useFaroStore((state) => state.updateTask)
  const [creating, setCreating] = useState(false), [adding, setAdding] = useState<SprintCommitment>(), [reviewing, setReviewing] = useState(false), [feedback, setFeedback] = useState('')
  const active = data.sprints.find((item) => item.status === 'active')
  const links = active ? data.sprintTasks.filter((item) => item.sprintId === active.id && !item.removedAt) : []
  const activeTasks = links.map((link) => ({ link, task: tasks.find((task) => task.id === link.taskId) })).filter((item) => item.task)
  const completed = activeTasks.filter(({ task }) => task?.status === 'done').length
  const outcomes = active ? data.outcomes.filter((item) => item.sprintId === active.id) : []
  const completedOutcomes = outcomes.filter((item) => item.status === 'completed').length
  const minutes = activeTasks.reduce((sum, { task }) => sum + (task?.estimatedMinutes ?? 0), 0)
  const progress = activeTasks.length ? completed / activeTasks.length * 100 : 0
  const saveOutcome = async (outcome: SprintOutcome, status: SprintOutcome['status']) => { if (!user) return; await sprintRepository.saveOutcome({ ...outcome, status }, user.id); await refresh() }
  if (loading && !data.sprints.length) return <div className="page"><div className="planning-skeleton">Preparando sprints…</div></div>
  return <div className="page sprint-page"><PageHeader eyebrow="Ejecución semanal" title="Sprints" description="Define qué debe cambiar esta semana y protege el trabajo comprometido." onCapture={capture} />
    {feedback && <div className="kanban-feedback" role="status">{feedback}</div>}
    {error && !data.sprints.length ? <EmptyState title="No pudimos cargar Sprints" description={error} action={<Button onClick={refresh}>Reintentar</Button>} /> : !active ? <><EmptyState title="No hay un sprint activo" description="Crea un ciclo flexible de siete días con un resultado principal." action={<Button icon={<Plus size={15} />} onClick={() => setCreating(true)}>Crear sprint</Button>} /><SprintHistory sprints={data.sprints} reviews={data.reviews} /></> : <>
      <header className="sprint-hero"><div><span className="eyebrow">Sprint actual</span><h1>{active.name}</h1><p>{format(parseISO(active.startDate), 'dd MMM')} — {format(parseISO(active.endDate), 'dd MMM yyyy')}</p></div><Button variant="secondary" onClick={() => setReviewing(true)}>Cerrar sprint</Button></header>
      <section className="sprint-metrics"><Metric label="Avance de tareas" value={`${Math.round(progress)}%`} /><Metric label="Comprometidas" value={`${links.filter((item) => item.commitmentType === 'committed').length}`} /><Metric label="Completadas" value={`${completed}`} /><Metric label="Emergentes" value={`${links.filter((item) => item.commitmentType === 'emergent').length}`} /><Metric label="Minutos previstos" value={`${minutes}`} /><Metric label="Capacidad restante" value={active.capacityMinutes == null ? 'Sin límite' : `${Math.max(0, active.capacityMinutes - minutes)} min`} /></section>
      <ProgressBar value={progress} />
      <div className="sprint-layout"><section className="sprint-outcomes"><header><span className="eyebrow">Resultados</span><strong>{completedOutcomes}/{outcomes.length}</strong></header>{outcomes.map((outcome) => <article key={outcome.id} className={outcome.status === 'completed' ? 'done' : ''}><button aria-label={`Completar ${outcome.title}`} onClick={() => void saveOutcome(outcome, outcome.status === 'completed' ? 'pending' : 'completed')}>{outcome.status === 'completed' ? <Check /> : <Target />}</button><div><small>{outcome.type === 'main' ? 'Principal' : 'Secundario'}</small><strong>{outcome.title}</strong></div><select aria-label={`Estado de ${outcome.title}`} value={outcome.status} onChange={(event) => void saveOutcome(outcome, event.target.value as SprintOutcome['status'])}><option value="pending">Pendiente</option><option value="in_progress">En progreso</option><option value="completed">Completado</option><option value="dropped">Descartado</option></select></article>)}</section>
        <section className="sprint-task-groups">{(Object.keys(commitmentLabels) as SprintCommitment[]).map((kind) => <div key={kind}><header><h2>{commitmentLabels[kind]}</h2><button onClick={() => setAdding(kind)}><Plus size={13} />Añadir</button></header>{activeTasks.filter(({ link }) => link.commitmentType === kind).map(({ link, task }) => task && <article key={link.id}><button className={task.status === 'done' ? 'complete' : ''} onClick={() => updateTask(task.id, { status: task.status === 'done' ? 'todo' : 'done' })}><Check size={13} /></button><div><strong>{task.title}</strong><small>{task.priority} · {task.estimatedMinutes ?? 0} min · {task.dueDate ?? 'sin fecha'}</small></div><select value={link.commitmentType} aria-label={`Categoría de ${task.title}`} onChange={async (event) => { if (!user) return; await sprintRepository.updateSprintTask(link.id, { commitment_type: event.target.value }, user.id); await refresh() }}>{Object.entries(commitmentLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><button aria-label={`Retirar ${task.title}`} onClick={async () => { if (!user) return; await sprintRepository.updateSprintTask(link.id, { removed_at: new Date().toISOString() }, user.id); await refresh() }}><X size={14} /></button></article>)}{!activeTasks.some(({ link }) => link.commitmentType === kind) && <p>Sin tareas.</p>}</div>)}</section>
      </div><SprintHistory sprints={data.sprints.filter((item) => item.id !== active.id)} reviews={data.reviews} />
    </>}
    {creating && <CreateSprintDialog userId={user?.id} onClose={() => setCreating(false)} onSaved={async () => { setCreating(false); await refresh(); setFeedback('Sprint creado.') }} />}
    {adding && active && <AddTasksDialog sprint={active} commitment={adding} tasks={tasks.filter((task) => !links.some((link) => link.taskId === task.id))} userId={user?.id} onClose={() => setAdding(undefined)} onSaved={async () => { setAdding(undefined); await refresh() }} />}
    {reviewing && active && <ReviewDialog sprint={active} userId={user?.id} onClose={() => setReviewing(false)} onSaved={async () => { setReviewing(false); await refresh(); setFeedback('Sprint cerrado.') }} />}
  </div>
}
function Metric({ label, value }: { label: string; value: string }) { return <article><span>{label}</span><strong>{value}</strong></article> }
function SprintHistory({ sprints, reviews }: { sprints: Sprint[]; reviews: SprintReview[] }) { const closed = sprints.filter((item) => item.status === 'completed'); return closed.length ? <section className="sprint-history"><span className="eyebrow">Historial</span>{closed.map((item) => <article key={item.id}><TimerReset /><div><strong>{item.name}</strong><small>{item.startDate} — {item.endDate}</small><p>{item.mainOutcome}</p>{reviews.find((review) => review.sprintId === item.id)?.lessons && <em>{reviews.find((review) => review.sprintId === item.id)?.lessons}</em>}</div></article>)}</section> : null }
function CreateSprintDialog({ userId, onClose, onSaved }: { userId?: string; onClose: () => void; onSaved: () => void }) {
  const today = format(new Date(), 'yyyy-MM-dd'), [name, setName] = useState('Sprint semanal'), [start, setStart] = useState(today), [end, setEnd] = useState(format(addDays(new Date(), 6), 'yyyy-MM-dd')), [main, setMain] = useState(''), [secondary, setSecondary] = useState(['', '', '']), [capacity, setCapacity] = useState(''), [notes, setNotes] = useState('')
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!userId) return; const id = crypto.randomUUID(); await sprintRepository.saveSprint({ id, name, startDate: start, endDate: end, status: 'active', mainOutcome: main, capacityMinutes: capacity ? Number(capacity) : undefined, notes: notes || undefined }, userId); await sprintRepository.saveOutcome({ id: crypto.randomUUID(), sprintId: id, title: main, type: 'main', status: 'pending', sortOrder: 0 }, userId); await Promise.all(secondary.filter(Boolean).map((title, index) => sprintRepository.saveOutcome({ id: crypto.randomUUID(), sprintId: id, title, type: 'secondary', status: 'pending', sortOrder: index + 1 }, userId))); onSaved() }
  return <Modal open title="Crear sprint" onClose={onClose}><form className="growth-form" onSubmit={submit}><label>Nombre<input autoFocus required value={name} onChange={(event) => setName(event.target.value)} /></label><div><label>Inicio<input type="date" required value={start} onChange={(event) => setStart(event.target.value)} /></label><label>Fin<input type="date" min={start} required value={end} onChange={(event) => setEnd(event.target.value)} /></label></div><label>Resultado principal<input required value={main} onChange={(event) => setMain(event.target.value)} /></label>{secondary.map((value, index) => <label key={index}>Resultado secundario {index + 1}<input value={value} onChange={(event) => setSecondary((current) => current.map((item, itemIndex) => itemIndex === index ? event.target.value : item))} /></label>)}<label>Capacidad en minutos<input type="number" min="0" value={capacity} onChange={(event) => setCapacity(event.target.value)} /></label><label>Notas<textarea rows={3} value={notes} onChange={(event) => setNotes(event.target.value)} /></label><div className="modal-actions"><Button type="button" variant="ghost" onClick={onClose}>Cancelar</Button><Button type="submit">Crear sprint</Button></div></form></Modal>
}
function AddTasksDialog({ sprint, commitment, tasks, userId, onClose, onSaved }: { sprint: Sprint; commitment: SprintCommitment; tasks: ReturnType<typeof useFaroStore.getState>['tasks']; userId?: string; onClose: () => void; onSaved: () => void }) { const [query, setQuery] = useState(''); const filtered = useMemo(() => tasks.filter((item) => item.title.toLowerCase().includes(query.toLowerCase())), [query, tasks]); return <Modal open title={`Añadir · ${commitmentLabels[commitment]}`} onClose={onClose}><div className="sprint-picker"><input autoFocus aria-label="Buscar tareas" placeholder="Buscar en Backlog…" value={query} onChange={(event) => setQuery(event.target.value)} />{filtered.map((task) => <button key={task.id} onClick={async () => { if (!userId) return; await sprintRepository.addTask(sprint.id, task.id, commitment, userId); onSaved() }}><strong>{task.title}</strong><small>{task.priority} · {task.status}</small></button>)}{!filtered.length && <p>No hay tareas disponibles.</p>}</div></Modal> }
function ReviewDialog({ sprint, userId, onClose, onSaved }: { sprint: Sprint; userId?: string; onClose: () => void; onSaved: () => void }) { const [summary, setSummary] = useState(''), [wins, setWins] = useState(''), [blockers, setBlockers] = useState(''), [lessons, setLessons] = useState(''), [carry, setCarry] = useState(''); const submit = async (event: FormEvent) => { event.preventDefault(); if (!userId) return; await sprintRepository.saveReview({ id: crypto.randomUUID(), sprintId: sprint.id, summary, wins, blockers, lessons, carryOverNotes: carry }, userId); await sprintRepository.saveSprint({ ...sprint, status: 'completed' }, userId); onSaved() }; return <Modal open title="Cerrar sprint" onClose={onClose}><form className="growth-form" onSubmit={submit}><label>Resumen<textarea required rows={3} value={summary} onChange={(event) => setSummary(event.target.value)} /></label><label>Principales logros<textarea rows={2} value={wins} onChange={(event) => setWins(event.target.value)} /></label><label>Bloqueos<textarea rows={2} value={blockers} onChange={(event) => setBlockers(event.target.value)} /></label><label>Aprendizajes<textarea rows={2} value={lessons} onChange={(event) => setLessons(event.target.value)} /></label><label>Tareas a mover o regresar al Backlog<textarea rows={2} value={carry} onChange={(event) => setCarry(event.target.value)} /></label><div className="modal-actions"><Button type="button" variant="ghost" onClick={onClose}>Cancelar</Button><Button type="submit">Cerrar sprint</Button></div></form></Modal> }
