import {act,renderHook} from '@testing-library/react'
import {afterEach,describe,expect,it,vi} from 'vitest'
import {useSpeechInput} from './useSpeechInput'
let instance:{onresult:((event:unknown)=>void)|null;onend:(()=>void)|null;onerror:((event:{error:string})=>void)|null;start:ReturnType<typeof vi.fn>;stop:ReturnType<typeof vi.fn>;abort:ReturnType<typeof vi.fn>}
class RecognitionMock{lang='';interimResults=false;continuous=false;onresult=null;onend=null;onerror=null;start=vi.fn();stop=vi.fn();abort=vi.fn();constructor(){
// eslint-disable-next-line @typescript-eslint/no-this-alias
instance=this}}
describe('entrada de voz del laboratorio',()=>{afterEach(()=>{delete (window as unknown as {webkitSpeechRecognition?:unknown}).webkitSpeechRecognition})
 it('transcribe sin enviar automáticamente y permite editar desde el consumidor',()=>{(window as unknown as {webkitSpeechRecognition:unknown}).webkitSpeechRecognition=RecognitionMock;const transcript=vi.fn();const {result}=renderHook(()=>useSpeechInput(transcript));act(()=>result.current.start());expect(instance.start).toHaveBeenCalled();act(()=>instance.onresult?.({results:[{0:{transcript:'pagué la licencia'}}]}));expect(transcript).toHaveBeenCalledWith('pagué la licencia')})
 it('ofrece fallback cuando SpeechRecognition no existe',()=>{const {result}=renderHook(()=>useSpeechInput(vi.fn()));expect(result.current.supported).toBe(false)})
 it('entrega parciales y autoenvía únicamente el resultado final',()=>{(window as unknown as {webkitSpeechRecognition:unknown}).webkitSpeechRecognition=RecognitionMock;const partial=vi.fn();const final=vi.fn();const {result}=renderHook(()=>useSpeechInput(partial,final));act(()=>result.current.start());act(()=>instance.onresult?.({results:[{0:{transcript:'renta'},isFinal:false}]}));expect(partial).toHaveBeenCalledWith('renta');expect(final).not.toHaveBeenCalled();act(()=>instance.onresult?.({results:[{0:{transcript:'la renta fueron 4350'},isFinal:true}]}));expect(final).toHaveBeenCalledWith('la renta fueron 4350')})
 it('aborta el reconocimiento al desmontarse para evitar eco o listeners vivos',()=>{(window as unknown as {webkitSpeechRecognition:unknown}).webkitSpeechRecognition=RecognitionMock;const {result,unmount}=renderHook(()=>useSpeechInput(vi.fn()));act(()=>result.current.start());unmount();expect(instance.abort).toHaveBeenCalled()})
 it('descarta dos eventos finales iguales recibidos en menos de dos segundos',()=>{(window as unknown as {webkitSpeechRecognition:unknown}).webkitSpeechRecognition=RecognitionMock;const final=vi.fn();const {result}=renderHook(()=>useSpeechInput(vi.fn(),final));act(()=>result.current.start(true));act(()=>{instance.onresult?.({results:[{0:{transcript:'confirmo'},isFinal:true}]});instance.onresult?.({results:[{0:{transcript:'confirmo'},isFinal:true}]})});expect(final).toHaveBeenCalledTimes(1);expect((instance as typeof instance & {continuous:boolean}).continuous).toBe(true)})
 it('normaliza puntuación al deduplicar y no inicia dos reconocimientos simultáneos',()=>{(window as unknown as {webkitSpeechRecognition:unknown}).webkitSpeechRecognition=RecognitionMock;const final=vi.fn();const {result}=renderHook(()=>useSpeechInput(vi.fn(),final));act(()=>{result.current.start(true);result.current.start(true)});expect(instance.start).toHaveBeenCalledTimes(1);act(()=>{instance.onresult?.({results:[{0:{transcript:'Sí, registra el pago.'},isFinal:true}]});instance.onresult?.({results:[{0:{transcript:'si registra el pago'},isFinal:true}]})});expect(final).toHaveBeenCalledTimes(1)})
 it('onend sólo libera el reconocimiento y no emite otra instrucción',()=>{(window as unknown as {webkitSpeechRecognition:unknown}).webkitSpeechRecognition=RecognitionMock;const final=vi.fn();const {result}=renderHook(()=>useSpeechInput(vi.fn(),final));act(()=>result.current.start(true));act(()=>instance.onend?.());expect(final).not.toHaveBeenCalled();expect(result.current.state).toBe('idle')})
})
