import { useCallback, useEffect, useRef, useState } from 'react'
type RecognitionEvent={results:ArrayLike<{0:{transcript:string};isFinal?:boolean}>} 
type Recognition={lang:string;interimResults:boolean;continuous:boolean;start():void;stop():void;abort():void;onresult:((e:RecognitionEvent)=>void)|null;onend:(()=>void)|null;onerror:((e:{error:string})=>void)|null}
type RecognitionCtor=new()=>Recognition
const constructor=()=>{const scope=window as unknown as {SpeechRecognition?:RecognitionCtor;webkitSpeechRecognition?:RecognitionCtor};return scope.SpeechRecognition??scope.webkitSpeechRecognition}
export function useSpeechInput(onTranscript:(value:string)=>void,onFinal?:(value:string)=>void){const ref=useRef<Recognition|null>(null);const lastFinal=useRef<{value:string;at:number}>({value:'',at:0});const [state,setState]=useState<'idle'|'listening'|'processing'|'error'|'denied'>('idle');const supported=Boolean(typeof window!=='undefined'&&constructor())
 const stop=useCallback(()=>{if(ref.current){setState('processing');ref.current.stop()}},[])
 const start=useCallback((continuous=false)=>{if(ref.current)return;const Ctor=constructor();if(!Ctor){setState('error');return}const recognition=new Ctor();ref.current=recognition;recognition.lang='es-MX';recognition.interimResults=true;recognition.continuous=continuous;recognition.onresult=(event)=>{const result=event.results[event.results.length-1];const value=result?.[0]?.transcript?.trim();if(value){onTranscript(value);if(result.isFinal){const normalized=value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9 ]/g,' ').replace(/\s+/g,' ').trim();const now=Date.now();if(lastFinal.current.value!==normalized||now-lastFinal.current.at>2000){lastFinal.current={value:normalized,at:now};onFinal?.(value)}}}};recognition.onerror=(event)=>setState(event.error==='not-allowed'||event.error==='service-not-allowed'?'denied':'error');recognition.onend=()=>{if(ref.current===recognition)ref.current=null;setState(current=>current==='denied'||current==='error'?current:'idle')};setState('listening');try{recognition.start()}catch{ref.current=null;setState('error')}},[onFinal,onTranscript])
 useEffect(()=>()=>{ref.current?.abort();ref.current=null},[]);return{supported,state,start,stop}}
