import { lazy } from 'react'

export const DashboardPage = lazy(() => import('../features/dashboard/DashboardPage').then((module) => ({ default: module.DashboardPage })))
export const LearningPage = lazy(() => import('../pages/LearningPage').then((module) => ({ default: module.LearningPage })))
export const FinancePage = lazy(() => import('../pages/FinancePage').then((module) => ({ default: module.FinancePage })))
export const HealthPage = lazy(() => import('../pages/HealthPage').then((module) => ({ default: module.HealthPage })))
export const JournalPage = lazy(() => import('../pages/JournalPage').then((module) => ({ default: module.JournalPage })))
export const BacklogPage = lazy(() => import('../features/backlog/BacklogPage').then((module) => ({ default: module.BacklogPage })))
export const TodayPage = lazy(() => import('../pages/TodayPage').then((module) => ({ default: module.TodayPage })))
export const CalendarPage = lazy(() => import('../pages/CalendarPage').then((module) => ({ default: module.CalendarPage })))
export const GoalsPage = lazy(() => import('../pages/GoalsPage').then((module) => ({ default: module.GoalsPage })))
export const GoalDetailPage = lazy(() => import('../pages/GoalDetailPage').then((module) => ({ default: module.GoalDetailPage })))
export const SettingsPage = lazy(() => import('../pages/SettingsPage').then((module) => ({ default: module.SettingsPage })))
export const TravelPage = lazy(() => import('../pages/TravelPage').then((module) => ({ default: module.TravelPage })))
export const SalesPage = lazy(() => import('../pages/SalesPage').then((module) => ({ default: module.SalesPage })))
export const ContentPage = lazy(() => import('../pages/ContentPage').then((module) => ({ default: module.ContentPage })))
export const PortfolioPage = lazy(() => import('../pages/PortfolioPage').then((module) => ({ default: module.PortfolioPage })))
export const SprintsPage = lazy(() => import('../pages/SprintsPage').then((module) => ({ default: module.SprintsPage })))
